version: "3"
services:
  client:
    tty: true
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
  server:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - ${HOST_WEBHOOK_PORT}:${HOST_WEBHOOK_PORT}
    command: "python host_employer/main.py"
  ngrok-host-employer:
    image: wernight/ngrok
    command: ngrok http host-employer-agent:${HOST_HTTP_PORT} --log stdout
  host-employer-agent:
    build:
      context: agent
      dockerfile: Dockerfile
    environment:
      NGROK_NAME: ngrok-host-employer
      AGENT_NAME: Blackpool Teaching Hospital
      PORT: ${LEAD_HTTP_PORT}
      ADMIN_PORT: ${HOST_ADMIN_PORT}
      WEBHOOK_URL: ${HOST_WEBHOOK_URL}
    ports:
      - ${HOST_HTTP_PORT}:${HOST_HTTP_PORT}
      - ${HOST_ADMIN_PORT}:${HOST_ADMIN_PORT}