version: "3"
services:
  client:
    tty: true
    build:
      context: client
      dockerfile: Dockerfile
    volumes:
      - ./client/src:/usr/src/app/src
    ports:
      - 3000:3000
    networks:
      - host-employer
    depends_on:
      - host-employer-agent
  server:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - 8000:8000
      - ${HOST_WEBHOOK_PORT}:${HOST_WEBHOOK_PORT}

    environment:
      WEBHOOK_HOST: 0.0.0.0
      ADMIN_URL: http://host-employer-agent:${HOST_ADMIN_PORT}
      WEBHOOK_PORT: ${HOST_WEBHOOK_PORT}
    networks:
      - host-employer
    command: "python -u host_employer/main.py"
  ngrok-host-employer:
    image: wernight/ngrok
    command: ngrok http host-employer-agent:${HOST_HTTP_PORT} --log stdout
    networks:
      - host-employer
  host-employer-agent:
    build:
      context: agent
      dockerfile: Dockerfile
    environment:
      NGROK_NAME: ngrok-host-employer
      AGENT_NAME: Blackpool Teaching Hospital
      PORT: ${HOST_HTTP_PORT}
      ADMIN_PORT: ${HOST_ADMIN_PORT}
      WEBHOOK_URL: ${HOST_WEBHOOK_URL}
    ports:
      - ${HOST_HTTP_PORT}:${HOST_HTTP_PORT}
      - ${HOST_ADMIN_PORT}:${HOST_ADMIN_PORT}
    networks:
      - host-employer
networks:
  host-employer:
